[package]
name = "relm-cairo-test"
version = "0.1.0"
authors = ["Nadir Sampaoli <nadirsampaoli@gmail.com>"]

[dependencies]
relm = "^0.14.0"
relm-derive = "^0.14.0"
cairo-rs = "*"
gtk = { version = "^0.4", features = ["v3_22"] }
gdk = "*"
gdk-pixbuf = "*"